server:
  port: 8081

spring:
  application:
    name: category-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ventas
    username: postgres
    password: admin
  data:
    jpa:
      repositories:
        enabled:  true

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/