server:
  port: 8085

spring:
  application:
    name: person-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ventas
    username: postgres
    password: admin
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379

token:
  client: apis-token-8331.ZgLYS--bYXV6b5BdMOjVWWfp7fu2YqI7
