server:
  port: 8086

spring:
  application:
    name: security-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ventas
    username: postgres
    password: postgres
  data:
    jpa:
      repositories:
        enabled: true
key:
  token:  85732b878c0f544da4a863804775ef3914e8ccb82b08820a278302c5b826e291