server:
  port: 8084

spring:
  application:
    name: venta-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ventas
    username: postgres
    password: postgres
  data:
    jpa:
      repositories:
        enabled:  true

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/