server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled:  true
      routes:
        - id: category-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/category/**
          filters:
            - name: AuthFilter
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**
          filters:
            - name: AuthFilter
        - id: permit-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/permit/**
            - Path=/api/permit-person/**
          filters:
            - name: AuthFilter
        - id: venta-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/sale/**
          filters:
            - name: AuthFilter
        - id: person-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/person/**
          filters:
            - name: AuthFilter
        - id: security-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/authentication/**
          filters:
            - name: AuthFilter

